# Generated by Django 6.0.2 on 2026-02-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='complete_by',
        ),
    ]
